# /vaultwarden/compose.yaml


# ----------------------------------------------------------------------------------

#
# Vaultwarden is a complete docker stack for self-hosting a password manager.
#
# This configuration sets up default properties for all containers, integrates
# Vaultwarden with a PostgreSQL database, and ensures it runs on the 'vaultwarden_network'.
#
# Services included:
# - vaultwarden: https://github.com/dani-garcia/vaultwarden

# -----------------------------------------------------------------------------------    

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - DOMAIN=${DOMAIN}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DISABLE_ADMIN_TOKEN=${DISABLE_ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - INVITATIONS_ALLOWED=${INVITATIONS_ALLOWED}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURITY=${SMTP_SECURITY}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}
      - EXTENDED_LOGGING=${EXTENDED_LOGGING}
      - SHOW_PASSWORD_HINT=${SHOW_PASSWORD_HINT}
      - WEB_VAULT_ENABLED=${WEB_VAULT_ENABLED}
      - IP_HEADER=${IP_HEADER}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
    env_file:
      - ${VAULTWARDEN_CONFIG_PATH}/.secrets.vaultwarden
    volumes:
      - ${VAULTWARDEN_CONFIG_PATH}/data:/data
    depends_on:
      - postgres
    networks:
      - vaultwarden_network
    ports:
      - "${VAULTWARDEN_PORT}:80"

  postgres:
    image: postgres:15-alpine
    container_name: vaultwarden_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${VAULTWARDEN_CONFIG_PATH}/postgres:/var/lib/postgresql/data
    networks:
      - vaultwarden_network

networks:
  vaultwarden_network:
    driver: bridge