# /caddy/compose.yaml


# ----------------------------------------------------------------------------------

#
# Caddy is a complete docker stack for serving web content with automatic HTTPS 
# and reverse proxy capabilities.
#
# This configuration sets up default properties for all containers, integrates
# Caddy with a custom configuration file, and ensures it runs on the 'proxy' network.
#
# Services included:
# - caddy: https://github.com/caddyserver/caddy

# -----------------------------------------------------------------------------------    

services:
  caddy:
    image: caddy:${CADDY_TAG}
    container_name: caddy-${CADDY_TAG}
    hostname: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${CADDY_CONFIG_PATH}/Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_CONFIG_PATH}/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    external: true