# /error-pages/compose.yaml


# ----------------------------------------------------------------------------------

#
# error-pages is a complete docker stack for handling HTTP errors with a 
# customizable template, integrated with Caddy for serving web content.
#
# Services included:
# - error-pages: https://github.com/tarampampam/error-pages

# -----------------------------------------------------------------------------------    

services:
  error-pages:
    image: ghcr.io/tarampampam/error-pages:3
    environment:
      TEMPLATE_NAME: l7
    networks:
      - proxy # Ensure this service is on the same network as Caddy

networks:
  proxy:
    external: true # Use the existing 'proxy' network for communication with Caddy
    name: proxy # Ensure the network name matches the one used in Caddy's compose file